# Generated by Django 2.0.4 on 2018-05-05 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default=datetime.datetime(2018, 5, 5, 20, 32, 32, 901675), max_length=200),
        ),
    ]
