# Generated by Django 2.0.4 on 2018-05-15 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180506_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='chapter_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='notes.Chapter'),
        ),
        migrations.AddField(
            model_name='file',
            name='subject_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='notes.Subject'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default=datetime.datetime(2018, 5, 16, 0, 33, 29, 500335), max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='time',
            field=models.CharField(default=datetime.datetime(2018, 5, 16, 0, 33, 29, 500335), max_length=200),
        ),
    ]
