# Generated by Django 2.0.4 on 2018-05-15 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20180516_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='subject_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default=datetime.datetime(2018, 5, 16, 0, 40, 11, 616053), max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='time',
            field=models.CharField(default=datetime.datetime(2018, 5, 16, 0, 40, 11, 615057), max_length=200),
        ),
    ]
