# Generated by Django 2.0.4 on 2018-05-15 19:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20180516_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='subject_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='notes.Subject'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default=datetime.datetime(2018, 5, 16, 0, 40, 49, 801412), max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='time',
            field=models.CharField(default=datetime.datetime(2018, 5, 16, 0, 40, 49, 801412), max_length=200),
        ),
    ]
